### ISSUE TITLE
V0.1.0 tracking

### ISSUE THREAD

**Issue by theunkn0wn1** [theunkn0wn1/themealdb-rs#1]
There are some outstanding features that need to be implemented prior to a release

Basic endpoints:
 - [x] `Search meal by name`
 - [x] `List all meals by first letter`
 - [x] `Lookup full meal details by id`
 - [x] `Lookup a single random meal`
 - [x] `List all meal categories`
 - [x] `List all Categories` (NOT to be confused with `List all meal categories`, this endpoint returns something else.)
 - [x] `List all areas`
 - [x] `List all Ingredients`
 - [x] `Filter by main ingredient`
 - [x] `Filter by Category`
 - [x] `Filter by Area`
 - [ ] #2

CI:
 - [x] #4
 - [ ] test suite

**Comment by theunkn0wn1** [comment]
#2 Will be differed since I don't have access to those endpoints and this API is very inconsistent.
